source $HOME/.config/nvim/settings/settings.vim
source $HOME/.config/nvim/settings/keymappings.vim
source $HOME/.config/nvim/plugins/vimplugged.vim
source $HOME/.config/nvim/plugins/nerdtree.vim
source $HOME/.config/nvim/plugins/onedark.vim
source $HOME/.config/nvim/plugins/lightline.vim
source $HOME/.config/nvim/plugins/markdownPreview.vim
source $HOME/.config/nvim/plugins/coc-keybinds.vim
luafile $HOME/.config/nvim/plugins/plug-colorizer.lua
